name: Déploiement IONOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Déploiement SFTP vers IONOS
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Déployer en SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: sftp
          server-dir: ./public/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/README.md
            **/.DS_Store
            **/Thumbs.db
